#!/bin/sh
# Install the `yue` launcher, the same way img/vid/snd/suno are installed.
#
# Everything is derived from where THIS script sits, so the repo can live anywhere.
#
#   ./install.sh                  # uv sync + launcher into ~/bin (or ~/.local/bin, or $BIN_DIR)
#   ./install.sh --cuda           # ...with the Linux/NVIDIA extra (vllm, triton, nvml)
#   ./install.sh --check          # report what is installed, change nothing
#
set -eu

REPO=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
BIN_DIR=${BIN_DIR:-}
CHECK_ONLY=0
EXTRA=""

while [ $# -gt 0 ]; do
	case "$1" in
		--check) CHECK_ONLY=1; shift ;;
		--cuda) EXTRA="--extra cuda"; shift ;;
		-h|--help) sed -n '2,8p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
		*) echo "unknown argument: $1" >&2; exit 2 ;;
	esac
done

if [ -z "$BIN_DIR" ]; then
	if [ -d "$HOME/bin" ]; then BIN_DIR="$HOME/bin"; else BIN_DIR="$HOME/.local/bin"; fi
fi

if [ "$CHECK_ONLY" = 1 ]; then
	echo "repo:    $REPO"
	echo "bin dir: $BIN_DIR"
	if [ -e "$BIN_DIR/yue" ]; then echo "  yue -> $(sed -n 's/^exec "\([^"]*\)".*/\1/p' "$BIN_DIR/yue")"; else echo "  yue  NOT INSTALLED"; fi
	[ -x "$REPO/.venv/bin/yue" ] || echo "WARNING: $REPO/.venv is not synced (run ./install.sh)"
	command -v ffmpeg >/dev/null 2>&1 || echo "WARNING: ffmpeg is not on PATH (needed for mp3 export, remix, --init-audio)"
	exit 0
fi

command -v uv >/dev/null 2>&1 || { echo "uv is not on PATH - https://docs.astral.sh/uv/" >&2; exit 1; }
# shellcheck disable=SC2086
uv sync --project "$REPO" $EXTRA

mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/yue" <<EOF
#!/bin/sh
# Generated by $REPO/install.sh - do not edit; re-run install.sh instead.
exec "$REPO/.venv/bin/yue" "\$@"
EOF
chmod +x "$BIN_DIR/yue"
echo "installed $BIN_DIR/yue -> $REPO/.venv/bin/yue"
